version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    container_name: pass-in-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pass-in-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
