spring:
  application:
    name: pass-in
  datasource:
    url: jdbc:postgresql://localhost:5432/pass-in-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    # hibernate:
      # ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
    open-in-view: false
    show-sql: true
